# Generated by Django 3.1.3 on 2021-01-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
    ]
