# Generated by Django 3.1.3 on 2021-01-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
        migrations.AlterField(
            model_name='настройка',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
